In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.randn(3,4)

tensor([[ 0.3327,  0.9649,  0.6435,  1.8641],
        [-1.0757, -0.9502, -1.5536,  0.2236],
        [ 1.2469, -0.5654, -0.7009, -0.2913]])

In [8]:
torch.tensor([1,2])

tensor([1, 2])

In [9]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.1,1,4,3], [1,2,3,4], [4,3,2,1]])
torch.cat((X,Y), dim=0)

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000],
        [ 2.1000,  1.0000,  4.0000,  3.0000],
        [ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000]])

In [10]:
torch.cat((X,Y), dim=1)

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  2.1000,  1.0000,  4.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  1.0000,  2.0000,  3.0000,  4.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  4.0000,  3.0000,  2.0000,  1.0000]])

In [11]:
X.sum()

tensor(66.)

In [12]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [13]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [14]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [18]:
X[1,2] = 8
X

tensor([[12., 12., 12., 12.],
        [12., 12.,  8., 12.],
        [ 8.,  9., 10., 11.]])

In [17]:
X[0:2 , :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [20]:
X[0:2 , 1:3] = 13
X

tensor([[12., 13., 13., 12.],
        [12., 13., 13., 12.],
        [ 8.,  9., 10., 11.]])

In [21]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [22]:
before = id(Y)
Y  += X
id(Y) == before

True

In [28]:
A = X.numpy()
A,type(A),id(A),id(X)

(array([[12., 13., 13., 12.],
        [12., 13., 13., 12.],
        [ 8.,  9., 10., 11.]], dtype=float32),
 numpy.ndarray,
 1715484542704,
 1715478796464)

In [29]:
B = torch.tensor(A)	
B,type(B),id(B),id(A)

(tensor([[12., 13., 13., 12.],
         [12., 13., 13., 12.],
         [ 8.,  9., 10., 11.]]),
 torch.Tensor,
 1715478030112,
 1715484542704)

In [34]:
a = torch.tensor([4.5])
a, a.item(), float(a)

(tensor([4.5000]), 4.5, 4.5)

In [42]:
a = torch.arange(4).reshape(4,1)
b = torch.arange(4).reshape(1,4)
a,b

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1, 2, 3]]))

In [43]:
a+b

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6]])