In [1]:
import torch
import numpy as np

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.randn(3,4)

tensor([[-0.6194, -0.0981,  0.0840,  0.7558],
        [-1.5340, -1.1699, -0.8937, -0.6121],
        [-0.1541, -1.4392, -1.2104, -1.4684]])

In [8]:
torch.tensor([1,2])

tensor([1, 2])

In [13]:
X = torch.arange(12, dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.1,1,4,3], [1,2,3,4], [4,3,2,1]])
torch.cat((X,Y), dim=0)

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000],
        [ 2.1000,  1.0000,  4.0000,  3.0000],
        [ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000]])

In [14]:
torch.cat((X,Y), dim=1)

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  2.1000,  1.0000,  4.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  1.0000,  2.0000,  3.0000,  4.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  4.0000,  3.0000,  2.0000,  1.0000]])

In [15]:
X.sum()

tensor(66.)

In [18]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [19]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])